"""Generate the static House Medical software studio website. No dependencies."""
from pathlib import Path
from html import escape
import json
ROOT = Path(__file__).resolve().parents[1]
EMAIL = 'sales@housemedical.co.uk'
ARROW = '<svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M5 19 19 5M5 5h14v14" stroke="currentColor" stroke-width="1.5"/></svg>'
RIGHT = '<svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M4 12h15M12 5l7 7-7 7" stroke="currentColor" stroke-width="1.5"/></svg>'
MARK = '<span class="logotype">house<span>.</span></span><span class="brand-caption">Software<br>studio</span>'
PAGES = []
def link(href,label,cls='text-link'):
 return f'<a class="{cls}" href="{href}"><span>{label}</span>{ARROW}</a>'
def header(active):
 return f'''<a class="skip-link" href="#main">Skip to content</a>
<header class="site-header"><div class="wrap header-inner"><a class="brand" href="/" aria-label="House Medical software studio home">{MARK}</a><button class="menu-toggle" aria-expanded="false" aria-controls="primary-nav" type="button"><span>Menu</span><span class="menu-symbol" aria-hidden="true">+</span></button><nav id="primary-nav" aria-label="Main navigation"><a href="/services/" {'aria-current="page"' if active=='services' else ''}>What we build</a><a href="/about/" {'aria-current="page"' if active=='about' else ''}>Our approach</a>{link('mailto:'+EMAIL,'Let’s talk','nav-cta')}</nav></div></header>'''
def footer(cta=True):
 return (f'''<section class="contact-cta"><div class="wrap"><p class="eyebrow">A good place to start</p><div class="contact-cta-row"><h2>Something<br>worth <em>building?</em></h2>{link('mailto:'+EMAIL,'Tell us about it','round-link')}</div><div class="cta-email">{link('mailto:'+EMAIL,EMAIL)}</div></div></section>''' if cta else '')+f'''<footer class="site-footer"><div class="wrap"><div class="footer-top"><p>Thoughtful software.<br>For the way life works.</p><div><a href="/services/">What we build</a><a href="/about/">Our approach</a><a href="/contact/">Contact</a></div><div><a href="/policies/data-protection-privacy/">Privacy</a><a href="/legal/">Company information</a></div></div><div class="footer-word" aria-hidden="true">house<span>.</span></div><div class="footer-bottom"><p>© <span data-year>2026</span> House Medical Consultants Ltd</p><span>Software, thoughtfully made.</span><a href="#top">Back to top ↑</a></div></div></footer>'''
def write(path,title,desc,body,active='',cta=True,extra=''):
 url='/' if path=='index.html' else '/'+path.removesuffix('index.html')
 page=f'''<!doctype html>
<html lang="en-GB" id="top">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>{escape(title)} | House Medical</title><meta name="description" content="{escape(desc,quote=True)}">
<meta name="theme-color" content="#f5f6f2"><link rel="canonical" href="https://housemedical.co.uk{url}">
<link rel="icon" type="image/svg+xml" href="/assets/favicon.svg">
<link rel="preload" as="font" type="font/ttf" href="/assets/manrope-regular.ttf" crossorigin>
<link rel="preload" as="font" type="font/ttf" href="/assets/manrope-bold.ttf" crossorigin>
<link rel="stylesheet" href="/assets/site.css"><script src="/assets/site.js" defer></script>
{extra}
<noscript><style>@media(max-width:760px){{.site-header{{height:auto}}.header-inner{{flex-wrap:wrap;padding-block:20px}}.menu-toggle{{display:none}}#primary-nav{{position:static;width:100%;display:flex;padding:10px 0;gap:20px;flex-wrap:wrap;border:0;box-shadow:none}}#primary-nav a{{font-size:.875rem;padding:8px 0}}}}</style></noscript>
</head><body>
{header(active)}
<main id="main">{body}</main>
{footer(cta)}
</body></html>'''
 p=ROOT/path;p.parent.mkdir(parents=True,exist_ok=True);p.write_text(page);PAGES.append(path)
def intro(kicker,title,desc):
 return f'<section class="wrap page-intro"><p class="eyebrow">{kicker}</p><h1>{title}</h1><p class="page-lede">{desc}</p></section>'
def discipline(number,title,desc,tags,cls):
 return f'<article class="discipline {cls}"><div class="discipline-top"><span class="eyebrow">{number} / What we build</span><span class="discipline-symbol" aria-hidden="true">{number}</span></div><h3>{title}</h3><p>{desc}</p><ul class="tags">'+''.join(f'<li>{t}</li>' for t in tags)+'</ul></article>'
def capabilities():
 items=[('01','Web applications','Useful products, from the first screen to the final step.','Clear journeys, responsive interfaces and the logic that makes everything work together.'),('02','Intelligent automation','Let software do the repetitive work.','Turn information into actions, simplify administration and use AI where it helps people get things done.'),('03','Connected services','Make the whole process work better.','Bring data and services together so people can complete a task without moving between disconnected systems.')]
 return '<div class="capabilities">'+''.join(f'<article class="capability"><span class="eyebrow">{n}</span><div><h3>{title}</h3><p class="capability-lead">{lead}</p></div><p>{desc}</p></article>' for n,title,lead,desc in items)+'</div>'
write('index.html','Software for real life','We design and build thoughtful software for business, public services and everyday life. Complex tasks, made simpler.',f'''
<section class="wrap hero"><div class="hero-kicker"><p class="eyebrow">Independent software studio</p><span class="eyebrow secondary-kicker">Ideas into useful things</span></div><h1>Complex tasks.<br><em>Simple software.</em></h1><div class="hero-bottom"><a class="discover-link" href="#work"><span>Discover what we build</span><span aria-hidden="true">↓</span></a><p>We turn complicated processes into clear, useful software — for businesses, public services and everyday life.</p></div></section>
<section class="outcome-band" aria-label="Our focus"><div class="wrap outcome-inner"><span>Less administration.</span><span>Clearer decisions.</span><span>Better experiences.</span></div></section>
<section class="wrap section work-section" id="work"><div class="section-heading"><div><p class="eyebrow">01 / What we build</p><h2>Different challenges.<br>The same <em>care.</em></h2></div><p>We build around the task people need to complete, and the things that get in their way.</p></div><div class="discipline-grid">{discipline('01','Business,<br>without the busywork.','Software that helps people understand their numbers, manage obligations and get everyday administration done.',['Business tools','Financial workflows','Intelligent automation'],'business')}{discipline('02','Public services.<br>Human experiences.','Tools that help people report a problem, share the right information and understand what happens next.',['Civic technology','Reporting tools','Connected services'],'civic')}</div><div class="section-tail"><p>Different sectors. A shared focus on making things work better.</p>{link('/services/','Explore our capabilities')}</div></section>
<section class="principle-section"><div class="wrap principle-inner"><div class="principle-heading"><p class="eyebrow">02 / The way we think</p><h2>The hard work<br>happens <em>behind<br>the simplicity.</em></h2></div><div class="principle-content"><p class="large-copy">A good product knows what to ask, what to handle and when to get out of the way.</p><p>We look closely at the rules, the information and the decisions behind a task. Then we design a clear path through them.</p><div class="process-diagram" aria-label="Our design approach: understand the task, simplify the journey, build the detail"><div><span>01</span><p>Understand<br>the task</p></div><span class="process-arrow" aria-hidden="true">→</span><div><span>02</span><p>Simplify<br>the journey</p></div><span class="process-arrow" aria-hidden="true">→</span><div><span>03</span><p>Build<br>the detail</p></div></div>{link('/about/','How we approach the work')}</div></div></section>
<section class="wrap section capabilities-section"><div class="section-heading"><div><p class="eyebrow">03 / From idea to product</p><h2>Made to be used.<br><em>Built to work.</em></h2></div></div>{capabilities()}</section>''')
write('services/index.html','What we build','Web applications, intelligent automation and connected services for business and the public sector.',intro('What we build','Useful software.<br><em>Real-world purpose.</em>','We build digital products around practical problems: the paperwork that takes too long, the process that is hard to follow, the service that could work better.')+f'''<section class="wrap service-overview"><div class="section-heading"><p class="eyebrow">Our capabilities</p><p>From the experience people see<br>to the systems that support it.</p></div>{capabilities()}</section><section class="work-context"><div class="wrap section"><div class="section-heading"><div><p class="eyebrow">Where it makes a difference</p><h2>Everyday complexity.<br><em>Thoughtfully resolved.</em></h2></div></div><div class="context-grid"><article><span class="eyebrow">Business &amp; finance</span><h3>Make the important<br>things easier.</h3><p>Guided workflows, clear information and tools that reduce the effort of running a business. Software should help people move from “what do I need to do?” to “that’s done”.</p><ul><li>Financial and administrative tools</li><li>Document and information workflows</li><li>Calculations and decision support</li></ul></article><article><span class="eyebrow">Public services</span><h3>A clearer connection<br>between people and services.</h3><p>Reporting tools and digital journeys that make it easier to describe a problem, provide useful information and understand the next step.</p><ul><li>Issue reporting and service requests</li><li>Guided information gathering</li><li>Clear status and next steps</li></ul></article></div></div></section><section class="wrap section final-note"><p class="eyebrow">A practical mindset</p><h2>The right technology<br>starts with the <em>right problem.</em></h2><p>We’re interested in what will make a product more useful. Sometimes that means automation or AI. Sometimes it means asking a better question, or removing a step altogether.</p>{link('/about/','See how we work')}</section>''',active='services')
steps=[('01','Understand.','Start with the task, not the screen.','Work out what people are trying to do, what information matters and where the process becomes difficult.'),('02','Simplify.','Make the next step feel obvious.','Turn that understanding into a clear journey. Use plain language, ask for what is needed and make important decisions visible.'),('03','Build.','Care about what happens underneath.','Bring the interface, business rules and integrations together. Pay attention to validation, errors and the less obvious cases.'),('04','Refine.','Keep learning from real use.','Look at where people need help, where they hesitate and what could work better. Improve the details that make a difference.')]
write('about/index.html','Our approach','Our approach to building software: understand the problem, simplify the journey, build with care and refine through use.',intro('Our approach','Start with the problem.<br><em>Stay with the detail.</em>','We believe useful software comes from understanding both the people who use it and the work it needs to do.')+f'''<section class="wrap approach-intro"><p class="eyebrow">The studio</p><div><h2>We make complicated<br>things feel <em>straightforward.</em></h2><p>House Medical builds software for business and public-service problems. Our focus is on practical products that give people a clearer way to complete an important task.</p><p>That takes thoughtful design and careful engineering. We treat them as parts of the same job.</p></div></section><section class="wrap approach-steps">'''+''.join(f'<article class="approach-step"><span class="step-number">{n}</span><h2>{title}</h2><div><h3>{lead}</h3><p>{desc}</p></div></article>' for n,title,lead,desc in steps)+f'''</section><section class="approach-statement"><div class="wrap"><p class="eyebrow">Our point of view</p><h2>Good software respects<br>people’s <em>time.</em></h2><p>It makes the important things clear, handles the complexity it can and helps people keep moving.</p></div></section>''',active='about')
write('contact/index.html','Get in touch','Contact House Medical about software, digital products and practical problems worth solving.',f'''<section class="wrap contact-page"><p class="eyebrow">Get in touch</p><h1>Start with<br><em>a conversation.</em></h1><div class="contact-body"><p>A problem to solve, an idea to explore, or a product you’d like to discuss. We’d like to hear about it.</p><div><span class="eyebrow">Email the studio</span>{link('mailto:'+EMAIL,EMAIL,'contact-email')}<p>Tell us a little about what you have in mind.</p></div></div></section>''',active='contact',cta=False)
write('policies/data-protection-privacy/index.html','Privacy','How House Medical handles information shared through this website and email.',intro('House Medical','A note on <em>privacy.</em>','How we handle information shared with us through this website.' )+f'''<section class="wrap legal-layout"><aside><span class="eyebrow">Questions?</span><a href="mailto:{EMAIL}">{EMAIL}</a></aside><article class="prose"><h2>This website</h2><p>This website introduces our software work. It does not have an enquiry form, advertising trackers or third-party analytics scripts. Fonts and visual assets are served with the site.</p><h2>If you contact us</h2><p>If you email us, we receive your email address, the information in your message and any attachments you choose to send. We use that information to respond and manage the conversation. Please only share information that is relevant to your enquiry.</p><h2>Service providers</h2><p>Our hosting and email providers process information needed to operate their services. This may include technical information about requests to the website and email delivery.</p><h2>Our software products</h2><p>Information about how a particular product handles data should be read alongside that product’s own privacy information and terms.</p><h2>Your information</h2><p>To ask about personal information you have shared with us, including a request to access, correct or delete it, email <a href="mailto:{EMAIL}">{EMAIL}</a>.</p></article></section>''',cta=False)
write('legal/index.html','Company information','Company and contact information for House Medical Consultants Ltd.',intro('Company information','The company<br><em>behind the software.</em>','House Medical is the software studio of House Medical Consultants Ltd.')+f'''<section class="wrap company-section"><dl class="company-details"><div><dt>Company name</dt><dd>House Medical Consultants Ltd</dd></div><div><dt>Company number</dt><dd>12540692</dd></div><div><dt>Contact</dt><dd><a href="mailto:{EMAIL}">{EMAIL}</a></dd></div></dl><p>This website provides an overview of our work. The availability, features and terms of individual products are described alongside those products.</p>{link('/policies/data-protection-privacy/','Privacy information')}</section>''',cta=False)
write('404.html','Page not found','The page could not be found.',intro('404 / Page not found','A small detour.<br><em>Let’s head back.</em>','The page may have moved, or the address may be incomplete.')+'<div class="wrap not-found-actions">'+link('/','Back to the studio','button-link')+'</div>',cta=False,extra='<meta name="robots" content="noindex">')
# Retire the healthcare content while keeping incoming links useful.
redirects={'blog/index.html':'/#work','careers/index.html':'/contact/','faq/index.html':'/services/','contact/thank-you.html':'/contact/','policies/index.html':'/policies/data-protection-privacy/'}
for name in ['diversity-equity-inclusion','environmental-policy','health-and-safety','modern-slavery','quality-management']:
 redirects[f'policies/{name}/index.html']='/legal/'
for path,target in redirects.items():
 p=ROOT/path;p.parent.mkdir(parents=True,exist_ok=True)
 p.write_text(f'<!doctype html>\n<html lang="en-GB"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>House Medical</title><meta name="robots" content="noindex"><link rel="canonical" href="https://housemedical.co.uk{target}"><meta http-equiv="refresh" content="0;url={target}"></head><body><main><h1>This page has moved.</h1><p><a href="{target}">Continue to House Medical</a></p></main></body></html>\n')
(ROOT/'assets/favicon.svg').write_text('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><rect width="64" height="64" rx="12" fill="#d9fb6c"/><text x="13" y="48" fill="#18211c" font-family="Arial,sans-serif" font-size="53" font-weight="700">h</text><circle cx="50" cy="47" r="4" fill="#18211c"/></svg>\n')
(ROOT/'sitemap.xml').write_text('<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+''.join('<url><loc>https://housemedical.co.uk'+('/' if p=='index.html' else '/'+p.removesuffix('index.html'))+'</loc></url>' for p in PAGES if p!='404.html')+'</urlset>\n')
(ROOT/'robots.txt').write_text('User-agent: *\nAllow: /\nDisallow: /dev/\nSitemap: https://housemedical.co.uk/sitemap.xml\n')
print(f'Built {len(PAGES)} pages and {len(redirects)} legacy redirects.')
